# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every day)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  # workflow_dispatch:
  # push: {branches: ["metrics"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
          
      - name: 🧑‍🤝‍🧑 People (Stars)
        uses: lowlighter/metrics@master
        with:
          filename: pics/metrics-stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: sqllex
          plugin_people: yes
          plugin_people_limit: 1000
          plugin_people_size: 35
          plugin_people_types: contributors, stargazers
          plugins_errors_fatal: ${{ github.repository == 'v1a0/sqllex' }}
